### PR TITLE
WIP: fixed the 'area' property for accumulate function

### PR DESCRIPTION
**Pull request by saubhagya-gatech**
```
'area' property added.

if ''CatchmentAreaSqKm'' property is requested by user

area='CatchmentAreaSqKm'*1e6

else

area= shapely area of catchment polygon
```

### CODE REVIEW

**Comment by saubhagya-gatech** [comment]
We need not to accumulate if 'TotalDrainageAreaSqKm' is requested by user. This edit is yet to be made in the code. This can be used for area based pruning functions

**Comment by ecoon** [comment]
Is there a reason this is WIP?  I'm going to merge it and fix it now if so, and will be adding a few more of the HydroSeq options today.

**Comment by saubhagya-gatech** [comment]
Sure, sounds good. You can merge this small change. I kept it WIP to make accumulate conditional on if "TotalDrainageAreaSqKm" is loaded by user. But I agree with your comment on requiring users to load 'CatchmentAreaSqKm'  and 'TotalDrainageAreaSqKm' as properties in order to use prune_by_* functions . 

'CatchmentAreaSqKm' = Catchment area, in square kilo- meters

'TotalDrainageAreaSqKm' = Total cumulative area, in square kilometers

**Comment by ecoon** [comment]
I'm going to merge this into a branch, then update that branch to do the change for requiring TotalDrainageAreaSqKm for prune_by_*, unless you beat me to it.

**Comment by ecoon** [comment]
refs #26

**Pull request merged**
